#!/usr/bin/env bash
# Dependency Update Skill
# Automatically checks for outdated dependencies and creates update PRs
# Usage: ./run.sh [--dry-run] [--branch <branch>] [--pr]

set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────────────────
DRY_RUN=false
CREATE_PR=false
BASE_BRANCH="main"
UPDATE_BRANCH="chore/dependency-updates-$(date +%Y%m%d)"
PYPROJECT_FILE="pyproject.toml"
LOG_PREFIX="[dependency-update]"

# ─── Argument Parsing ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --pr)
      CREATE_PR=true
      shift
      ;;
    --branch)
      BASE_BRANCH="$2"
      shift 2
      ;;
    *)
      echo "$LOG_PREFIX Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

# ─── Helpers ──────────────────────────────────────────────────────────────────
log() { echo "$LOG_PREFIX $*"; }
err() { echo "$LOG_PREFIX ERROR: $*" >&2; }

require_cmd() {
  if ! command -v "$1" &>/dev/null; then
    err "Required command not found: $1"
    exit 1
  fi
}

# ─── Preflight Checks ─────────────────────────────────────────────────────────
require_cmd python
require_cmd pip
require_cmd git

if [[ ! -f "$PYPROJECT_FILE" ]]; then
  err "$PYPROJECT_FILE not found in $(pwd)"
  exit 1
fi

log "Starting dependency update check (dry_run=$DRY_RUN, create_pr=$CREATE_PR)"

# ─── Check for Outdated Packages ──────────────────────────────────────────────
log "Installing pip-audit and pip tools..."
pip install --quiet --upgrade pip pip-audit uv 2>/dev/null || true

log "Checking for outdated packages..."
OUTDATED_JSON=$(pip list --outdated --format=json 2>/dev/null || echo "[]")
OUTDATED_COUNT=$(echo "$OUTDATED_JSON" | python -c "import sys,json; data=json.load(sys.stdin); print(len(data))" 2>/dev/null || echo "0")

if [[ "$OUTDATED_COUNT" -eq 0 ]]; then
  log "All dependencies are up to date. Nothing to do."
  exit 0
fi

log "Found $OUTDATED_COUNT outdated package(s):"
echo "$OUTDATED_JSON" | python -c "
import sys, json
data = json.load(sys.stdin)
for pkg in data:
    print(f'  {pkg[\"name\"]}: {pkg[\"version\"]} -> {pkg[\"latest_version\"]}  ({pkg[\"latest_filetype\"]})')
"

# ─── Security Audit ───────────────────────────────────────────────────────────
log "Running security audit with pip-audit..."
AUDIT_OUTPUT=$(pip-audit --format=json 2>/dev/null || echo '{"vulnerabilities":[]}')
VULN_COUNT=$(echo "$AUDIT_OUTPUT" | python -c "
import sys, json
try:
    data = json.load(sys.stdin)
    vulns = data.get('vulnerabilities', data if isinstance(data, list) else [])
    print(len(vulns))
except Exception:
    print(0)
" 2>/dev/null || echo "0")

if [[ "$VULN_COUNT" -gt 0 ]]; then
  log "WARNING: $VULN_COUNT security vulnerability/vulnerabilities detected!"
else
  log "No known security vulnerabilities found."
fi

# ─── Dry Run Exit ─────────────────────────────────────────────────────────────
if [[ "$DRY_RUN" == "true" ]]; then
  log "Dry run complete. No changes applied."
  exit 0
fi

# ─── Apply Updates ────────────────────────────────────────────────────────────
log "Creating update branch: $UPDATE_BRANCH"
git checkout -b "$UPDATE_BRANCH" "origin/$BASE_BRANCH" 2>/dev/null || git checkout -b "$UPDATE_BRANCH" "$BASE_BRANCH"

log "Upgrading packages via uv..."
uv lock --upgrade 2>/dev/null || pip install --upgrade $(echo "$OUTDATED_JSON" | python -c "
import sys, json
data = json.load(sys.stdin)
print(' '.join(pkg['name'] for pkg in data))
")

# Regenerate lock file if it exists
if [[ -f "uv.lock" ]]; then
  log "Regenerating uv.lock..."
  uv lock
fi

# ─── Commit Changes ───────────────────────────────────────────────────────────
UPDATE_SUMMARY=$(echo "$OUTDATED_JSON" | python -c "
import sys, json
data = json.load(sys.stdin)
lines = [f'{p[\"name\"]} {p[\"version\"]}→{p[\"latest_version\"]}' for p in data[:5]]
if len(data) > 5:
    lines.append(f'...and {len(data)-5} more')
print(', '.join(lines))
")

git add -A
git diff --cached --quiet && { log "No file changes after update. Exiting."; exit 0; }
git commit -m "chore(deps): update $OUTDATED_COUNT dependencies

Updated: $UPDATE_SUMMARY

Security vulnerabilities found: $VULN_COUNT
Generated by dependency-update skill on $(date -u +%Y-%m-%dT%H:%M:%SZ)"

log "Changes committed to branch $UPDATE_BRANCH"

# ─── Create Pull Request ──────────────────────────────────────────────────────
if [[ "$CREATE_PR" == "true" ]]; then
  require_cmd gh
  log "Pushing branch and creating PR..."
  git push origin "$UPDATE_BRANCH"

  PR_BODY="## Dependency Updates\n\nThis PR was automatically generated by the dependency-update skill.\n\n"
  PR_BODY+="### Updated Packages ($OUTDATED_COUNT)\n\n"
  PR_BODY+=$(echo "$OUTDATED_JSON" | python -c "
import sys, json
data = json.load(sys.stdin)
rows = ['| Package | Old | New |', '|---------|-----|-----|']
for p in data:
    rows.append(f'| {p[\"name\"]} | {p[\"version\"]} | {p[\"latest_version\"]} |')
print('\\n'.join(rows))
")
  if [[ "$VULN_COUNT" -gt 0 ]]; then
    PR_BODY+="\n\n> ⚠️ **$VULN_COUNT security vulnerability/vulnerabilities** were detected. Please review carefully."
  fi

  gh pr create \
    --title "chore(deps): update $OUTDATED_COUNT outdated dependencies" \
    --body "$(printf '%b' "$PR_BODY")" \
    --base "$BASE_BRANCH" \
    --head "$UPDATE_BRANCH" \
    --label "dependencies"

  log "Pull request created successfully."
else
  log "Skipping PR creation (use --pr flag to create a PR)."
  log "Branch ready: $UPDATE_BRANCH"
fi

log "Dependency update complete."
